connector:
    name: Demo Connector
    jobs:
        demo_product_export:
            title: pim_base_connector.jobs.demo_product_export.title
            type:  export
            steps:
                export:
                    title: pim_base_connector.jobs.demo_product_export.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: pim_base_connector.processor.product_to_flat_array
                        writer:    pim_base_connector.writer.file.csv_product
        demo_dummy_export:
            title: pim_base_connector.jobs.demo_dummy_export.title
            type:  export
            steps:
                export:
                    title: pim_base_connector.jobs.demo_dummy_export.export.title
                    services:
                        reader:    pim_base_connector.reader.dummy
                        processor: pim_base_connector.processor.dummy
                        writer:    pim_base_connector.writer.dummy
        demo_custom_export:
            title: pim_base_connector.jobs.demo_custom_export.title
            type:  export
            steps:
                export:
                    title: pim_base_connector.jobs.demo_custom_export.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.bulk_product
                        processor: pim_base_connector.processor.csv_serializer.product
                        writer:    pim_base_connector.writer.product_file
                notify:
                    title: pim_base_connector.jobs.demo_custom_export.notify.title
                    class: "%acme_democonnector.step.notify.class%"
                    services:
                        handler: acme_democonnector.handler.curl
