services:
    acme_democonnector.transformer.guesser.comment:
        class: Acme\Bundle\DemoConnectorBundle\Transformer\Guesser\CommentGuesser
        arguments:
            - '@pim_import_export.transformer.property.skip'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }
