parameters:
    acme_dummy_connector.job.job_parameters.default_values_provider.dummy_export.class:        Acme\Bundle\DummyConnectorBundle\Job\JobParameters\DefaultValuesProvider\DummyExport
    acme_dummy_connector.job.job_parameters.constraint_collection_provider.dummy_export.class: Acme\Bundle\DummyConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\DummyExport
    acme_dummy_connector.job.job_parameters.form_configuration_provider.dummy_export.class:    Acme\Bundle\DummyConnectorBundle\Job\JobParameters\FormConfigurationProvider\DummyExport

services:
    # Default values for our JobParameters
    acme_dummy_connector.job.job_parameters.default_values_provider.dummy_export:
        class: '%acme_dummy_connector.job.job_parameters.default_values_provider.dummy_export.class%'
        arguments:
            -
                - 'dummy_job' # the job name
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    # Validation constraints for our JobParameters
    acme_dummy_connector.job.job_parameters.constraint_collection_provider.dummy_export:
        class: '%acme_dummy_connector.job.job_parameters.constraint_collection_provider.dummy_export.class%'
        arguments:
            -
                - 'dummy_job' # the job name
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    # Form configuration for our JobParameters
    acme_dummy_connector.job.job_parameters.form_configuration_provider.dummy_export:
        class: '%acme_dummy_connector.job.job_parameters.form_configuration_provider.dummy_export.class%'
        arguments:
            -
                - 'dummy_job' # the job name
        tags:
            - { name: pim_import_export.job_parameters.form_configuration_provider }
