parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: akeneo_pim
    database_user: root
    database_password: root
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    installer_data: 'AcmeInstallerBundle:mydataset'
