services:
    pim_enrich.view_element.attribute.tab.parameter:
        class: Acme\Bundle\EnrichBundle\View\Tab\MyCustomTab
        arguments:
            - 'pim_enrich.attribute.tab.parameter'
            - '%pim_enrich.view_element.attribute.tab.parameter.template%'
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_attribute_form.form_tab, position: 90 }


