services:
    acme_custom_mass_action.job.capitalize_values:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'mass_edit_capitalize_values'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@acme_custom_mass_action.step.capitalize_values.mass_edit'
        tags:
            - { name: akeneo_batch.job, connector: '%pim_enrich.connector_name.mass_edit%', type: '%pim_enrich.job.mass_edit_type%' }
