services:
    acme_custom_mass_action.mass_edit.capitalize_values.processor:
        class: Acme\Bundle\CustomMassActionBundle\Connector\Processor\MassEdit\Product\CapitalizeValuesProcessor
        arguments:
            - '@pim_catalog.updater.product_property_setter'
            - '@pim_catalog.validator.product'
