Acme\Bundle\CatalogBundle\Entity\MyCategory:
    type: entity
    repositoryClass: Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\CategoryRepository
    fields:
        description:
            type: string
            length: 255
