Acme\Bundle\CatalogBundle\Entity\MyCategory:
    type: entity
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\CategoryRepository
    fields:
        image:
            type: string
            length: 100
            nullable: false
