connector:
    name: Notify Connector
    jobs:
        notify_product_import:
            title: acme_notify_connector.jobs.notify_product_import.title
            type:  export
            steps:
                export:
                    title: acme_notify_connector.jobs.notify_product_import.export.title
                    services:
                        reader:    pim_connector.reader.file.csv_product
                        processor: pim_connector.processor.denormalization.product.flat
                        writer:    pim_connector.writer.doctrine.product
                notify:
                    title: acme_notify_connector.jobs.notify_product_import.notify.title
                    class: "%acme_notifyconnector.step.notify.class%"
                    services:
                        handler: acme_notifyconnector.handler.curl
