parameters:
    acme_notifyconnector.job.job_parameters.constraint_collection_provider.csv_product_export_notify.class: Acme\Bundle\NotifyConnectorBundle\JobParameters\ProductCsvExportNotify

services:
    acme_notifyconnector.job.job_parameters.constraint_collection_provider.csv_product_export_notify:
        class: '%acme_notifyconnector.job.job_parameters.constraint_collection_provider.csv_product_export_notify.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.product_csv_export'
            - '@pim_import_export.job_parameters.form_configuration_provider.product_csv_export'
            - '@pim_connector.job.job_parameters.constraint_collection_provider.product_csv_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
            - { name: pim_import_export.job_parameters.form_configuration_provider }
