parameters:
    acme_notifyconnector.step.notify.class: Acme\Bundle\NotifyConnectorBundle\Step\NotifyStep

services:
    acme_notifyconnector.step.notify:
        class: '%acme_notifyconnector.step.notify.class%'
        arguments:
            - 'notify'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
