services:
    pim_icecat_demo.transformer.property.entity:
        class: '%pim_transform.transformer.entity.class%'
        arguments:
            - '@pim_transform.entity_cache'
        public: false
        tags:
            - name: pim_import_export.transformer.product.attribute
              backend_type: vendor
              class: PimIcecatDemoBundle:Vendor
