parameters:
    pim_catalog.entity.product_value.class: Acme\Bundle\CatalogBundle\Entity\MyProductValue
    pim_catalog.entity.category.class: Acme\Bundle\CatalogBundle\Entity\Category
    pim_catalog.entity.category_translation.class: Acme\Bundle\CatalogBundle\Entity\CategoryTranslation
